name: Post a welcome comment
on: 
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  write_to_PR:
    name: write_to_PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: git checkout -b main
      - run: gh pr comment $PR_URL --body "I did my first github action"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html.url }}
